# Generated by Django 5.2 on 2025-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_casestudyimage_image_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event')], default='NEWS', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, help_text='The full content of the article. Optional.'),
        ),
        migrations.AddField(
            model_name='news',
            name='event_date_end',
            field=models.DateTimeField(blank=True, help_text='End date and time of the event.', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='event_date_start',
            field=models.DateTimeField(blank=True, help_text='Start date and time of the event.', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(blank=True, help_text="Location of the event, e.g., 'Düsseldorf, Germany'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(help_text='A short summary or introduction for the news/event.'),
        ),
    ]
