# Generated by Django 5.2 on 2025-05-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('TOM_PVC-O', 'TOM PVC-O Pipes'), ('FITTINGS', 'Fittings'), ('VALVES', 'Valves')], default='TOM_PVC-O', max_length=50)),
                ('water_application', models.CharField(choices=[('POTABLE', 'Potable water supply'), ('IRRIGATION', 'Irrigation'), ('INDUSTRIAL', 'Industrial'), ('WASTEWATER', 'Wastewater')], default='POTABLE', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('constructor', models.CharField(blank=True, max_length=100)),
                ('promoter', models.CharField(blank=True, max_length=100)),
                ('total_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specifications', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('issued_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_studies/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.casestudy')),
            ],
        ),
    ]
